version: '3'
services:
    mongo-oauth:
        image: 'mongo:4.0.4'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME2}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD2}'
            MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE2}'
            MONGODB_USER: '${MONGODB_USER2}'
            MONGODB_DATABASE: '${MONGODB_DATABASE2}'
            MONGODB_PASS: '${MONGODB_PASS2}'
        env_file:
            - ./.env
        ports:
            - '27017:27017'
        volumes:
            - './mongo-init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
    mongo-express-oauth:
        image: 'mongo-express:0.49'
        restart: always
        ports:
            - '10081:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: mongo-oauth
            ME_CONFIG_MONGODB_PORT: 27017
        links:
            - mongo-oauth
