version: '3'
services:
  mongo-oauth:
    container_name: 'mongo-oauth'
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_PASSwORD: ${MONGODB_PASS}
    ports:
      - 27017:27017
    env_file:
      .env
    volumes:
      - ./mongo-volume-express2:/data/db
      - ./mongo-settings/mongo-init.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  mongo-express-oauth:
    image: mongo-express:0.49
    restart: always
    ports:
      - 10081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo-oauth
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo-oauth
    depends_on:
      - mongo-oauth